/**
 * Generates `ap-brand-config.php` — a tiny WordPress plugin baked per customer.
 * On activation it writes all the brand options the data-driven theme reads
 * (name, tokens, fonts, copy) and sideloads the bundled logo/hero images. An
 * agent just uploads + activates it alongside the theme; no manual option editing.
 */

/** Escape a value for a single-quoted PHP string. */
const php = (s: unknown): string => String(s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");

export function generateBrandConfigPlugin(opts: {
  brandName: string;
  tokens: Record<string, string>;
  fontsUrl: string;
  copy: Record<string, string>;
  hasLogo: boolean;
  hasHero: boolean;
  hasHomeHtml: boolean;
}): string {
  const tokensJson = JSON.stringify(opts.tokens);

  const copyLines = Object.entries(opts.copy)
    .map(([k, v]) => {
      const key = k.toLowerCase().replace(/[^a-z0-9_]/g, '');
      if (!key) return '';
      return `    update_option( 'ap_copy_${php(key)}', '${php(v)}' );`;
    })
    .filter(Boolean)
    .join('\n');

  return `<?php
/**
 * Plugin Name: AP Brand Config — ${opts.brandName.replace(/[\r\n*/]/g, '')}
 * Description: Applies this customer's branding (name, palette, fonts, copy, logo, hero) to the Anchored-Peptides-style theme. Generated by Peptide Site Studio.
 * Version: 1.0.0
 */
if ( ! defined( 'ABSPATH' ) ) exit;

register_activation_hook( __FILE__, 'ap_brand_config_apply' );
// Also run on init once, so activating the theme after this plugin still applies.
add_action( 'init', function () {
    if ( get_option( 'ap_brand_config_applied' ) !== '1' ) ap_brand_config_apply();
} );

function ap_brand_config_apply() {
    update_option( 'blogname', '${php(opts.brandName)}' );
    update_option( 'ap_brand_tokens', '${php(tokensJson)}' );
    update_option( 'ap_fonts_url', '${php(opts.fontsUrl)}' );
${copyLines}

    // Sideload bundled brand images if present next to this plugin.
    ap_brand_config_sideload( 'logo', 'ap_logo_id' );
    ap_brand_config_sideload( 'hero', 'ap_hero_image_id' );

    // Custom homepage HTML (the reviewed/edited design) becomes the front page.
    $home = plugin_dir_path( __FILE__ ) . 'assets/home.html';
    if ( file_exists( $home ) ) {
        $html = @file_get_contents( $home );
        if ( $html !== false ) update_option( 'ap_custom_home_html', $html );
    }

    update_option( 'ap_brand_config_applied', '1' );
}

function ap_brand_config_sideload( $stem, $option ) {
    if ( get_option( $option ) ) return; // already set
    $matches = glob( plugin_dir_path( __FILE__ ) . 'assets/' . $stem . '.*' );
    if ( empty( $matches ) ) return;
    $src = $matches[0];
    require_once ABSPATH . 'wp-admin/includes/file.php';
    require_once ABSPATH . 'wp-admin/includes/media.php';
    require_once ABSPATH . 'wp-admin/includes/image.php';
    $svg = function ( $m ) { $m['svg'] = 'image/svg+xml'; return $m; };
    add_filter( 'upload_mimes', $svg );
    $tmp  = wp_tempnam( $src );
    @copy( $src, $tmp );
    $file = array( 'name' => basename( $src ), 'tmp_name' => $tmp );
    $id   = media_handle_sideload( $file, 0 );
    remove_filter( 'upload_mimes', $svg );
    if ( ! is_wp_error( $id ) ) update_option( $option, (int) $id );
    else @unlink( $tmp );
}
`;
}
